### ISSUE TITLE
mapper文件里好像少了几个文件，上传时候出问题了还是忘了上传啊

### ISSUE THREAD

**Issue by acceleratelch** [zyk-miao/open_flutter_music_back#1]

**Comment by zyk-miao** [comment]
什么问题?

**Comment by zyk-miao** [comment]
IDEA选择构建->重新构建项目 
![图片](https://user-images.githubusercontent.com/45023244/233838623-f56e1bef-92e6-4939-96e8-c3b99fc4d604.png)
参考阿里巴巴的fluentmybatis
