### ISSUE TITLE
不好意思，前两天在做别的事情，看到issue关闭了，后端项目那里还是有些问题，方便得知您的邮箱吗，想要问您一些问题

### ISSUE THREAD

**Issue by acceleratelch** [zyk-miao/open_flutter_music_back#2]

**Comment by zyk-miao** [comment]
你发你的邮箱吧

**Comment by acceleratelch** [comment]
> 你发你的邮箱吧

邮箱：3063315673@qq.com  QQ号同名，麻烦了

**Comment by acceleratelch** [comment]
> > 你发你的邮箱吧
> 
> 邮箱：[3063315673@qq.com](mailto:3063315673@qq.com) QQ号同名，麻烦了


> > 你发你的邮箱吧
> 
> 邮箱：[3063315673@qq.com](mailto:3063315673@qq.com) QQ号同名，麻烦了
